#!/bin/sh

commit_msg=$(cat "$1")
# Conventional Commits regex: type(scope?): subject
if ! echo "$commit_msg" | grep -Eq '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?: .+'; then
  echo "❌ Commit message must follow Conventional Commits format: type(scope?): subject"
  exit 1
fi
